POST http://localhost:55556/proxy
content-type: application/json

{
  "url": "https://echo.free.beeceptor.com",
  "method": "GET",
  "body": "",
  "headers": {}
}

###

POST http://localhost:55556/proxy
content-type: application/json

{
  "url": "https://api.rawg.io/api/games?search= s.t.a.l.k.e.r. 2: heart of chornobyl&key=d67d626470764ac288686e2b2a6a7289",
  "method": "GET",
  "body": "",
  "headers": {}
}

###

POST http://localhost:55556/proxy
content-type: application/json

{
  "url": "https://echo.free.beeceptor.com",
  "method": "POST",
  "body": "{\"a\":1}",
  "headers": {
    "content-type":"application/json",
    "test":"123",
    "auth":"pass"
  }
}
